site_name: Common Fund Data Ecosystem Documentation

repo_url: https://github.com/nih-cfde/published-documentation

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
  features:
    - tabs
  logo: images/CFDE_Logo-color-web.png

docs_dir: docs


markdown_extensions:
- admonition
- pymdownx.emoji
- codehilite:
    guess_lang: false
- toc:
    permalink: true
extra:
  hypothesis: true
extra_css:
  - stylesheets/extra.css
plugins:
  - mkdocs-jupyter:
      include_source: True
#  - htmlproofer
  - exclude:
      glob:
        - the-fair-cookbook/content/1/testnb/*
  - search: # necessary for search to work
      separator: '[\s\-\.]+'
  - awesome-pages
