name: Update c2m2 stable
on:
  schedule:
   - cron:  '1 */1 * * *'
jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token:  ${{ secrets.ALLTHEACTIONS }}
      - name: Update C2M2 submodule preview
        env:
          GITHUB_TOKEN: ${{ secrets.ALLTHEACTIONS }}
          ID_CFDEBOT: ${{ secrets.id_cfdebot }}
        run: |
          mkdir $HOME/.ssh && echo "$ID_CFDEBOT" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa && git submodule update --init --recursive --remote docs/C2M2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.5.0
        with:
            base: stable
            token: ${{ secrets.ALLTHEACTIONS }}
            commit-message: Update stable
            title: Auto update C2M2 submodule to stable
            body: |
              Your preview was generated at: https://cfde-published-documentation.readthedocs-hosted.com/en/C2M2preview/
              - Dependency updates
              - requires review

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            labels: proposedC2M2update
            branch: update-C2M2
            reviewers: Acharbonneau, marisalim, abradyIGS
